# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "042be27c44a48f1d50d5ec4a189e8a48"
application_url = "https://tracky-ordertrack.site/"
embedded = true
name = "Tracky"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_custom_fulfillment_services,write_custom_fulfillment_services,write_draft_orders,read_draft_orders,read_fulfillment_constraint_rules,write_fulfillment_constraint_rules,read_fulfillments,write_fulfillments,read_inventory_purchase_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,customer_read_draft_orders,customer_read_orders,customer_write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://tracky-ordertrack.site/api/shopify/callback" ]

[webhooks]
api_version = "2026-07"

[app_proxy]
url = "https://tracky-ordertrack.site/proxy/track-order"
subpath = "track-order"
prefix = "apps"
